release_production:
  extends:
    - .func_release
    - .only-cache-pull
  variables:
    IMAGE: ${AWS_PROD_CONTAINER_REGISTRY}/$CI_PROJECT_NAME
    AWS_CLUSTER_NAME: $AWS_PROD_CLUSTER_NAME
    AWS_ACCESS_KEY_ID: $AWS_PROD_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_PROD_SECRET_ACCESS_KEY
  only:
    - master
  needs:
    - build

deploy_production:
  stage: deploy
  image: jshimko/kube-tools-aws:3.5.0
  variables:
    SERVER_PORT: 9000
    NODE_ENV: production
    REPLICA_COUNT: 2
    HOST: api.coodesh.com
    MONGO_REPLICA_SET_STATUS: "on"
    MONGO_REPLICA_SET_SRV: "on"
    MONGO_REPLICA_SET_NAME: "atlas-swv97c-shard-0"
    MONGO_REPLICA_SET_HOSTS: vor.04atn.mongodb.net
    MONGO_SECRET: mongodb-credentials
    MONGO_DB: coodesh
    IMAGE: ${AWS_PROD_CONTAINER_REGISTRY}/$CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA
    AWS_CLUSTER_NAME: $AWS_PROD_CLUSTER_NAME
    AWS_ACCESS_KEY_ID: $AWS_PROD_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_PROD_SECRET_ACCESS_KEY
  script:
    - init_aws
    - run_helm
  cache: {}
  dependencies: []
  only:
    refs:
      - master
  environment:
    name: production
    url: https://${HOST}
  needs:
    - release_production

publish_production:
  stage: deploy
  script:
    - init_deps
    - npx semantic-release
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
    policy: pull
  only:
    refs:
      - master
  allow_failure: true
